### ISSUE TITLE
应用启动监听后没有收到请求，也没有其他逻辑发起请求，就会一直打印日志

### ISSUE THREAD

**Issue by Hsirehc** [cloudwego/hertz#603] opened 2023-02-07 10:06 UTC
**Describe the Question**

在vpc环境下应用启动监听后没有收到请求，也没有其他逻辑发起请求，就会一直打印这个日志，看请求地址是请求vpc下其他服务器的端口
2023/02/07 17:21:08.112555 engine.go:434: [Error] HERTZ: Error=read tcp 192.168.1.243:9957->100.117.153.1:18302: wsarecv: An existing connection was forcibly closed by the remote host., remoteAddr=100.117.153.1:18302
2023/02/07 17:21:08.527573 engine.go:434: [Error] HERTZ: Error=read tcp 192.168.1.243:9957->100.117.0.130:20775: wsarecv: An existing connection was forcibly closed by the remote host., remoteAddr=100.117.0.130:20775
2023/02/07 17:21:09.395728 engine.go:434: [Error] HERTZ: Error=read tcp 192.168.1.243:9957->100.117.152.131:35028: wsarecv: An existing connection was forcibly closed by the remote host., remoteAddr=100.117.152.131:35028

**Reproducible Code**
`h := server.Default(server.WithHostPorts(":9957"), server.WithMaxRequestBodySize(50<<20))`
`h.Spin()`

**Hertz version:**

v0.3.2

**Comment by welkeyever** [comment] 2023-02-07 11:14
Seems that “An existing connection was forcibly closed by the remote host” does not belong to Hertz.
I cannot reproduce this through the codes you paste above.
Could you please grep this error message locally to find where it came from?

**Comment by welkeyever** [comment] 2023-02-07 11:23
Is your hertz project deployed on Windows? 
If so, it maybe the error that client actively closes the connection - which can be ignored - probably is triggered by the idle timeout by client side.

**Comment by Hsirehc** [comment] 2023-02-08 01:46
应用是部署在windows上的

**Comment by Hsirehc** [comment] 2023-02-08 01:46
> Is your hertz project deployed on Windows? If so, it maybe the error that client actively closes the connection - which can be ignored - probably is triggered by the idle timeout by client side.

应用是部署在windows上的

**Comment by welkeyever** [comment] 2023-02-08 06:30
> > Is your hertz project deployed on Windows? If so, it maybe the error that client actively closes the connection - which can be ignored - probably is triggered by the idle timeout by client side.
> 
> 应用是部署在windows上的

Okay, just like what I said above, this error can be ignored.
If you don't wanna see this error on the server side, try config a shorter idle timeout for the server - let server trigger the closing action of the connection.

fyi: https://www.cloudwego.io/zh/docs/hertz/reference/config/

**Closed by welkeyever** 2023-02-08 06:30 UTC
Labels: question
